#!/usr/bin/env bash
#
# OpenJ5 Secrets Generation Script
#
# Generates all secret files required by docker-compose.yml:
#   - db_password.txt      (PostgreSQL password, must match .env DB_PASSWORD)
#   - grafana_password.txt (Grafana admin password)
#   - ota_signing_key.pem  (ECDSA P-256 private key for OTA firmware signing)
#
# Also creates/updates .env so DB_PASSWORD stays in sync with db_password.txt.
#
# Usage:
#   bash secrets/generate.sh                 # create missing secrets
#   bash secrets/generate.sh --force         # overwrite existing secrets
#
# Run from: firmware/node1_robot_core/docker/

set -euo pipefail

SECRETS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$(dirname "$SECRETS_DIR")"
ENV_FILE="$DOCKER_DIR/.env"

FORCE=0

for arg in "$@"; do
    case "$arg" in
        --force) FORCE=1 ;;
    esac
done

log() { printf "\033[1;34m[openj5]\033[0m %s\n" "$*"; }
die() { printf "\033[1;31m[openj5]\033[0m ERROR: %s\n" "$*"; exit 1; }

command -v openssl >/dev/null 2>&1 || die "openssl not found. Install with: sudo apt install openssl"

mkdir -p "$SECRETS_DIR"

gen_password() {
    openssl rand -hex 24
}

ensure_password_file() {
    local file="$1"
    if [ -f "$file" ] && [ "$FORCE" -eq 0 ]; then
        log "Already exists, keeping: $(basename "$file")"
        return 0
    fi
    gen_password > "$file"
    chmod 600 "$file"
    log "Generated: $(basename "$file")"
}

# ------------------------------------------------------------
# 1. PostgreSQL password (and .env DB_PASSWORD sync)
# ------------------------------------------------------------

ensure_password_file "$SECRETS_DIR/db_password.txt"

DB_PASSWORD="$(cat "$SECRETS_DIR/db_password.txt")"

if [ -f "$ENV_FILE" ] && [ "$FORCE" -eq 0 ]; then
    if grep -q '^DB_PASSWORD=' "$ENV_FILE"; then
        log ".env already defines DB_PASSWORD (use --force to reset)"
    else
        printf '\nDB_PASSWORD=%s\n' "$DB_PASSWORD" >> "$ENV_FILE"
        log "Added DB_PASSWORD to .env"
    fi
else
    printf '# OpenJ5 docker-compose environment variables\n# Auto-generated by secrets/generate.sh - NEVER commit\n\nDB_PASSWORD=%s\n' "$DB_PASSWORD" > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    log "Created .env with DB_PASSWORD"
fi

# ------------------------------------------------------------
# 2. Grafana admin password
# ------------------------------------------------------------

ensure_password_file "$SECRETS_DIR/grafana_password.txt"

# ------------------------------------------------------------
# 3. OTA signing key (ECDSA P-256)
# ------------------------------------------------------------

if [ -f "$SECRETS_DIR/ota_signing_key.pem" ] && [ "$FORCE" -eq 0 ]; then
    log "Already exists, keeping: ota_signing_key.pem"
else
    openssl ecparam -name prime256v1 -genkey -noout -out "$SECRETS_DIR/ota_signing_key.pem"
    chmod 600 "$SECRETS_DIR/ota_signing_key.pem"
    log "Generated: ota_signing_key.pem"
fi

# ------------------------------------------------------------
# Verify
# ------------------------------------------------------------

if [ "$(cat "$SECRETS_DIR/db_password.txt")" != "$DB_PASSWORD" ]; then
    die "db_password.txt and .env DB_PASSWORD mismatch!"
fi

log ""
log "Secrets generation complete."
log "  - db_password.txt      -> PostgreSQL password"
log "  - grafana_password.txt -> Grafana admin password"
log "  - ota_signing_key.pem  -> OTA signing key"
log ""
log "IMPORTANT: these files are SECRETS and are NEVER committed to git."
log "Run: docker compose up -d"
